# Generated by Django 5.2.4 on 2025-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
