# Generated by Django 5.2.4 on 2025-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
